import type { NextConfig } from "next";
import fs from "fs";
import path from "path";

const SITE = process.env.DATA ?? "main";
const activeFile = path.join(process.cwd(), "./", "data.ts");

// ✅ generate the file on dev + build
fs.writeFileSync(
  activeFile,
  `// Auto-generated by next.config.ts
export * from "@/data/${SITE}";
`
);

const nextConfig: NextConfig = {

  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'media.totalcareservicesfl.com',
      },
      {
        protocol: 'http',
        hostname: 'localhost',
      },
    ],
  },


};

export default nextConfig;